New upstream version 1.97+20091130

diff --git a/util/sparc64/ieee1275/grub-install.in b/util/sparc64/ieee1275/grub-install.in
--- a/util/sparc64/ieee1275/grub-install.in
+++ b/util/sparc64/ieee1275/grub-install.in
@@ -31,12 +31,11 @@ target_cpu=@target_cpu@
 platform=@platform@
 pkglibdir=${libdir}/`echo ${PACKAGE_TARNAME}/${target_cpu}-${platform} | sed ${transform}`
 
+# for make_system_path_relative_to_its_root()
+. ${libdir}/grub/grub-mkconfig_lib
+
 grub_setup=${sbindir}/`echo grub-setup | sed ${transform}`
-if [ "${target_cpu}-${platform}" = "i386-pc" ] ; then
-    grub_mkimage=${bindir}/`echo grub-mkimage | sed ${transform}`
-else
-    grub_mkimage=${bindir}/`echo grub-mkelfimage | sed ${transform}`
-fi
+grub_mkimage=${bindir}/`echo grub-mkimage | sed ${transform}`
 grub_mkdevicemap=${sbindir}/`echo grub-mkdevicemap | sed ${transform}`
 grub_probe=${sbindir}/`echo grub-probe | sed ${transform}`
 rootdir=
@@ -48,12 +47,6 @@ no_floppy=
 force_lba=
 recheck=no
 debug=no
-
-if [ "${target_cpu}-${platform}" = "i386-pc" ] ; then
-    disk_module=biosdisk
-else
-    disk_module=ata
-fi
 
 # Usage: usage
 # Print the usage.
@@ -73,14 +66,6 @@ Install GRUB on your drive.
   --grub-probe=FILE       use FILE as grub-probe
   --no-floppy             do not probe any floppy drive
   --recheck               probe a device map even if it already exists
-  --force                 install even if problems are detected
-EOF
-if [ "${target_cpu}-${platform}" = "i386-pc" ] ; then
-    cat <<EOF
-  --disk-module=MODULE    disk module to use
-EOF
-fi
-    cat <<EOF
 
 INSTALL_DEVICE can be a GRUB device name or a system device filename.
 
@@ -117,15 +102,9 @@ for option in "$@"; do
 	no_floppy="--no-floppy" ;;
     --recheck)
 	recheck=yes ;;
-    --disk-module=*)
-	if [ "${target_cpu}-${platform}" = "i386-pc" ] ; then
-           disk_module=`echo "$option" | sed 's/--disk-module=//'`
-        fi ;;
     # This is an undocumented feature...
     --debug)
 	debug=yes ;;
-    -f | --force)
-        setup_force="--force" ;;
     -*)
 	echo "Unrecognized option \`$option'" 1>&2
 	usage
@@ -141,9 +120,6 @@ for option in "$@"; do
     esac
 done
 
-# for make_system_path_relative_to_its_root()
-. ${libdir}/grub/grub-mkconfig_lib
-
 if test "x$install_device" = x; then
     echo "install_device not specified." 1>&2
     usage
@@ -158,33 +134,19 @@ if test $debug = yes; then
 fi
 
 # Initialize these directories here, since ROOTDIR was initialized.
-case "$host_os" in
-netbsd* | openbsd*)
-    # Because /boot is used for the boot block in NetBSD and OpenBSD, use /grub
-    # instead of /boot/grub.
-    grub_prefix=`echo /grub | sed ${transform}`
-    bootdir=${rootdir}
-    ;;
-*)
-    # Use /boot/grub by default.
-    bootdir=${rootdir}/boot
-    ;;
-esac
-
+bootdir=${rootdir}/boot
 grubdir=${bootdir}/`echo grub | sed ${transform}`
 device_map=${grubdir}/device.map
 
 grub_probe="${grub_probe} --device-map=${device_map}"
 
 # Check if GRUB is installed.
-if [ "${target_cpu}-${platform}" = "i386-pc" ] ; then
-    set $grub_setup dummy
-    if test -f "$1"; then
-        :
-    else
-        echo "$1: Not found." 1>&2
-        exit 1
-    fi
+set $grub_setup dummy
+if test -f "$1"; then
+    :
+else
+    echo "$1: Not found." 1>&2
+    exit 1
 fi
 
 set $grub_mkimage dummy
@@ -231,7 +193,7 @@ if test -n "$tmp"; then
 fi
 
 # Copy the GRUB images to the GRUB directory.
-for file in ${grubdir}/*.mod ${grubdir}/*.lst ${grubdir}/*.img ${grubdir}/efiemu??.o; do
+for file in ${grubdir}/*.mod ${grubdir}/*.lst ${grubdir}/*.img; do
     if test -f $file && [ "`basename $file`" != menu.lst ]; then
 	rm -f $file || exit 1
     fi
@@ -239,13 +201,10 @@ done
 for file in ${pkglibdir}/*.mod ${pkglibdir}/*.lst; do
     cp -f $file ${grubdir} || exit 1
 done
-if [ "${target_cpu}-${platform}" = "i386-pc" ] ; then
-    for file in ${pkglibdir}/*.img ${pkglibdir}/efiemu??.o; do
-	if test -f $file; then
-	    cp -f $file ${grubdir} || exit 1
-	fi
-    done
-fi
+
+for file in ${pkglibdir}/*.img; do
+    cp -f $file ${grubdir} || exit 1
+done
 
 # Write device to a variable so we don't have to traverse /dev every time.
 grub_device=`$grub_probe --target=device ${grubdir}`
@@ -266,8 +225,6 @@ partmap_module=`$grub_probe --target=partmap --device ${grub_device} 2> /dev/nul
 # Device abstraction module, if any (lvm, raid).
 devabstraction_module=`$grub_probe --target=abstraction --device ${grub_device}`
 
-# The order in this list is critical.  Be careful when modifying it.
-modules="$modules $disk_module"
 modules="$modules $fs_module $partmap_module $devabstraction_module"
 
 prefix_drive=
@@ -280,18 +237,9 @@ if [ "x${devabstraction_module}" = "x" ] ; then
     grub_drive="`$grub_probe --target=drive --device ${grub_device}`"
 
     # Strip partition number
-    install_drive="`echo ${install_drive} | sed -e s/,[0-9]*[a-z]*//g`"
-    grub_drive="`echo ${grub_drive} | sed -e s/,[0-9]*[a-z]*//g`"
-    if [ "$disk_module" = ata ] ; then
-        # generic method (used on coreboot and ata mod)
-        uuid="`$grub_probe --target=fs_uuid --device ${grub_device}`"
-        if [ "x${uuid}" = "x" ] ; then
-          echo "UUID needed with ata mod, but the filesystem containing ${grubdir} does not support UUIDs." 1>&2
-          exit 1
-        fi
-        prefix_drive="(UUID=${uuid})"
-        modules="$modules fs_uuid"
-    elif [ "x${grub_drive}" != "x${install_drive}" ] ; then
+    install_drive="`echo ${install_drive} | sed -e 's/\([^\]\),[0-9]*/\1/g'`"
+    grub_drive="`echo ${grub_drive} | sed -e 's/\([^\]\),[0-9]*/\1/g'`"
+    if [ "x${grub_drive}" != "x${install_drive}" ] ; then
         uuid="`$grub_probe --target=fs_uuid --device ${grub_device}`"
         if [ "x${uuid}" = "x" ] ; then
           echo "You attempted a cross-disk install, but the filesystem containing ${grubdir} does not support UUIDs." 1>&2
@@ -309,17 +257,20 @@ if [ "x${relative_grubdir}" = "x" ] ; then
     relative_grubdir=/
 fi
 
-if [ "${target_cpu}-${platform}" = "i386-pc" ] ; then
-    $grub_mkimage --output=${grubdir}/core.img --prefix=${prefix_drive}${relative_grubdir} $modules || exit 1
+$grub_mkimage --output=${grubdir}/core.img --prefix=${prefix_drive}${relative_grubdir} $modules || exit 1
 
-    # Now perform the installation.
-    $grub_setup ${setup_verbose} ${setup_force} --directory=${grubdir} --device-map=${device_map} \
+# Now perform the installation.
+$grub_setup ${setup_verbose} --directory=${grubdir} --device-map=${device_map} \
         ${install_device} || exit 1
-else
-    $grub_mkimage -d ${pkglibdir} --output=/boot/multiboot.img --prefix=${prefix_drive}${relative_grubdir} $modules || exit 1
-fi
 
+# Prompt the user to check if the device map is correct.
 echo "Installation finished. No error reported."
+echo "This is the contents of the device map $device_map."
+echo "Check if this is correct or not. If any of the lines is incorrect,"
+echo "fix it and re-run the script \`grub-install'."
+echo
+
+cat $device_map
 
 # Bye.
 exit 0
